//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArabaKirala
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int payment_id { get; set; }
        public Nullable<int> rental_id { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public decimal payment_amount { get; set; }
        public string payment_method { get; set; }
        public string payment_status { get; set; }
    
        public virtual Rentals Rentals { get; set; }
    }
}
